fix/ha_role_failure
mila-iqia/ansible-collection-proxmox pull request #9
Opened 2022-03-31 11:29 UTC by achillemyette1

fixes https://github.com/mila-iqia/ansible-collection-proxmox/issues/8

2022-04-06 14:24 UTC, btravouillon requested changes

2022-04-06 14:28 UTC, ahmam submitted a review, later dismissed

2022-04-20 08:11 UTC, achillemyette1 commented on roles/ha/tasks/main.yml
> +  register: ressources
fixed

2022-04-20 08:11 UTC, achillemyette1 commented on roles/ha/tasks/main.yml
> +  register: ressources
fixed

2022-04-20 08:17 UTC, pbouchez approved these changes

2022-04-20 12:40 UTC, btravouillon approved these changes
Looks good to me. 👍

2022-04-20 12:42 UTC, merged